--ITEM 1.2 DO EXERCICIO

-- (A)
ALTER TABLE T_MC_CLIENTE
    DROP CONSTRAINT UK_MC_CLIENTE_NOME_CLIENTE;
-- (B)
ALTER TABLE T_MC_CLIENTE
    MODIFY QT_ESTRELAS NOT NULL;
    
ALTER TABLE T_MC_CLIENTE
    MODIFY ST_CLIENTE NOT NULL;
   
ALTER TABLE T_MC_CLIENTE
    MODIFY DS_EMAIL NOT NULL;
-- (C)    
ALTER TABLE T_MC_CLIENTE
    ADD CONSTRAINT UN_NM_LOGIN UNIQUE (NM_LOGIN); 
-- (D)
ALTER TABLE T_MC_CLI_JURIDICA
    MODIFY DT_FUNDACAO NOT NULL;
    
ALTER TABLE T_MC_CLI_JURIDICA
    MODIFY NR_CNPJ NOT NULL; 
--(E)
ALTER TABLE T_MC_SGV_VISUALIZACAO_VIDEO
    MODIFY NR_MINUTO_VIDEO NOT NULL;
    
ALTER TABLE T_MC_SGV_VISUALIZACAO_VIDEO
    MODIFY NR_SEGUNDO_VIDEO NOT NULL;

-- (F)- FOI INLCUIDO O COMENTARIO NA COLUNA ST_END DA TABELA T_MC_END_FUNC

SELECT t.table_name as Tabelas, 
       c.column_name as colunas
  FROM all_tab_columns c, 
       all_tables t               
 WHERE c.column_name in('ST_PRODUTO',
                        'ST_VIDEO_PROD',
                        'ST_END','ST_FUNC',
                        'ST_CATEGORIA')
   AND c.table_name = t.table_name;

SELECT * FROM T_MC_CATEGORIA_PROD;
SELECT * FROM T_MC_END_CLI;
SELECT * FROM T_MC_END_FUNC;
SELECT *FROM T_MC_FUNCIONARIO;
SELECT * FROM T_MC_PRODUTO;
SELECT * FROM T_MC_SGV_PRODUTO_VIDEO;