-- 1_4 DO EXERCICIO
-- (A)
SELECT *FROM T_MC_CATEGORIA_PROD;
SELECT * FROM T_MC_PRODUTO;

SELECT C.CD_CATEGORIA    "COD. CATEGORIA",
       C.DS_CATEGORIA    "CATEGORIA",
       P.CD_PRODUTO    "COD. PRODUTO",
       P.DS_PRODUTO    "PRODUTO",
       P.VL_UNITARIO    " VALOR UNITARIO",
       P.TP_EMBALAGEM   "TIPO DE EMBALAGEM",
       P.VL_PERC_LUCRO  " PERCENTUAL DE LUCRO"
  FROM T_MC_CATEGORIA_PROD C,
       T_MC_PRODUTO P
WHERE C.CD_CATEGORIA = P.CD_CATEGORIA
   ORDER BY C.CD_CATEGORIA ASC;
       
-- (B)CRIANDO CONSULTA PARA AGRUPAR CLIENTES POR ESTADO , CIDADE E BAIRRO

SELECT * FROM T_MC_END_CLI;
SELECT * FROM T_MC_LOGRADOURO;
SELECT * FROM T_MC_BAIRRO;
SELECT * FROM T_MC_CIDADE;
SELECT * FROM  T_MC_ESTADO;

SELECT COUNT(NR_CLIENTE)  "QTDE CLIENTE", 
       E.NM_ESTADO   "NOME DO ESTADO",
       D.NM_CIDADE   "NOME DA CIDADE",
       C.NM_BAIRRO   "NOME DO BAIRRO" 
  FROM T_MC_LOGRADOURO A
INNER JOIN T_MC_END_CLI B
ON A.CD_LOGRADOURO = B.CD_LOGRADOURO_CLI
INNER JOIN T_MC_BAIRRO C
ON A.CD_BAIRRO = C.CD_BAIRRO
INNER JOIN T_MC_CIDADE D
ON C.CD_CIDADE = D.CD_CIDADE
INNER JOIN T_MC_ESTADO E
ON D.SG_ESTADO = E.SG_ESTADO
GROUP BY  E.NM_ESTADO, D.NM_CIDADE, C.NM_BAIRRO;

-- (C)CRIANDO CONSULTA PARA EXIBIR TOP 10 VIDEOS DE PRODUTOS

SELECT ROWNUM as RANK ,
         P.CD_PRODUTO ,
         P.DS_PRODUTO,
         TO_CHAR (T.DT_VISUALIZACAO, 'YYYY'),
         TO_CHAR (T.DT_VISUALIZACAO, 'MM')
 FROM        
     (SELECT 
       P.CD_PRODUTO    "COD. PRODUTO",
       P.DS_PRODUTO    "PRODUTO",
       TO_CHAR (T. DT_VISUALIZACAO, 'YYYY')   "ANO VISUALIZACAO"  ,
       TO_CHAR (T.DT_VISUALIZACAO, 'MM')   "MES VISUALIZACAO" ,
        COUNT(*) "TOTAL VISUALIZACAO"
  FROM T_MC_SGV_VISUALIZACAO_VIDEO T ,
       T_MC_PRODUTO P
       WHERE P.CD_PRODUTO = T.CD_PRODUTO
    GROUP BY P.CD_PRODUTO,
             P.DS_PRODUTO ,
             T.DT_VISUALIZACAO, 
    TO_CHAR (T. DT_VISUALIZACAO, 'YYYY'),
    TO_CHAR (T.DT_VISUALIZACAO, 'MM')
    ORDER BY "TOTAL VISUALIZACAO" DESC
    )
WHERE ROWNUM <= 10 ;

-- (D) CRIANDO CONSULTA PARA EXIBIR OS DADOS DO CLIENTE PF

SELECT * FROM T_MC_CLI_FISICA;
SELECT * FROM T_MC_CLIENTE;

SELECT C.NR_CLIENTE    "COD. CLIENTE",
       C.NM_CLIENTE    "NOME CLIENTE",
       C.DS_EMAIL    "E-MAIL",
       C.NR_TELEFONE    "TELEFONE",
       C.NM_LOGIN    " LOGIN",
       F.DT_NASCIMENTO   "DATA NASCIMENTO",
       F.FL_SEXO_BIOLOGICO  " SEXO BIOLOGICO",
       F.NR_CPF   "CPF"
  FROM T_MC_CLIENTE C,
       T_MC_CLI_FISICA F
WHERE C.NR_CLIENTE = F.NR_CLIENTE;

-- (E) CRIANDO CONSULTA PARA EXIBIR OS DADOS DO CLIENTE PJ

SELECT C.NR_CLIENTE    "COD. CLIENTE",
       C.NM_CLIENTE    "NOME CLIENTE",
       C.DS_EMAIL    "E-MAIL",
       C.NR_TELEFONE    "TELEFONE",
       C.NM_LOGIN    " LOGIN",
       J.DT_FUNDACAO   "DATA FUNDACAO",
       J.NR_CNPJ   "CNPJ"
  FROM T_MC_CLIENTE C,
      T_MC_CLI_JURIDICA J
WHERE C.NR_CLIENTE = J.NR_CLIENTE;

--(F) 
 
SELECT TO_CHAR(t.DT_VISUALIZACAO, 'DAY') dia_semana, 
       COUNT(*) "QTDE DE VISUALIZACAO"
  FROM T_MC_SGV_VISUALIZACAO_VIDEO t
     GROUP BY t.DT_VISUALIZACAO, 
      TO_CHAR(t.DT_VISUALIZACAO, 'DAY')
     ORDER BY "QTDE DE VISUALIZACAO" DESC;
     
-- (G) 

SELECT TO_CHAR (t. DT_ABERTURA_SAC, 'YYYY')   "ANO ABERTURA DO CHAMADO"  ,
        TO_CHAR (t.DT_ABERTURA_SAC, 'MM')   "MES ABERTURA DO CHAMADO" ,
        COUNT(*) "QTDE DE CHAMADO"
  FROM T_MC_SGV_SAC t
    GROUP BY t.DT_ABERTURA_SAC,
    TO_CHAR (t. DT_ABERTURA_SAC, 'YYYY'),
    TO_CHAR (t.DT_ABERTURA_SAC, 'MM')
    ORDER BY "QTDE DE CHAMADO" DESC;

-- (H) 


-- (I)
SELECT F.CD_FUNCIONARIO     "COD FUNCIONARIO",
       F.NM_FUNCIONARIO   "NOME FUNCIONARIO",
       F. DS_CARGO      "CARGO",
       D. NM_DEPTO     "DEPARTAMENTO",
       AVG (S.NR_INDICE_SATISFACAO)   "MÉDIA DE SATISFACAO POR FUNC" 
  FROM T_MC_FUNCIONARIO F,
       T_MC_DEPTO D,
       T_MC_SGV_SAC S 
   WHERE F. ST_FUNC = 'A'
     AND F.CD_DEPTO = D.CD_DEPTO
     AND S.CD_FUNCIONARIO = F.CD_FUNCIONARIO
   GROUP BY F.CD_FUNCIONARIO ,
       F.NM_FUNCIONARIO,   
       F. DS_CARGO,     
       D. NM_DEPTO   
       
SELECT * FROM T_MC_SGV_SAC;

-- (J)

SELECT P.CD_PRODUTO  "COD PRODUTO",
       P.DS_PRODUTO    "NOME PRODUTO",
       P.VL_UNITARIO  "VALOR PRODUTO",
       P.ST_PRODUTO  "STATUS DO PRODUTO",
  (V.NR_SEQUENCIA) "TOTAL DE VIDEO"
    FROM T_MC_PRODUTO P
     INNER JOIN  T_MC_SGV_PRODUTO_VIDEO V
  ON(P.CD_PRODUTO = V.CD_PRODUTO);